"""GitHub adapter — emit governance config from a charter.

Unlike the humanlayer/langgraph stubs, this target is **real**: it turns a
charter's gates and accountability into a CODEOWNERS starting point and a
branch-protection checklist you apply in GitHub. AgenRACI still does not enforce
anything at runtime — this is static config a human reviews and commits. A
charter governs action *types*, not file paths, so the CODEOWNERS lines are a
scaffold you scope to your repo.
"""

from __future__ import annotations

from ..schema import Charter


def _humans_in_role(charter: Charter, role: str) -> list[str]:
    """Human members holding ``role`` (agents can't be GitHub code owners)."""
    return [m.name for m in charter.members if m.role == role and m.type == "human"]


def _handles(names: list[str]) -> str:
    return " ".join(f"@{n}" for n in names)


def compile(charter: Charter) -> str:  # noqa: A001 - mirror CLI "compile" verb
    """Emit CODEOWNERS + branch-protection guidance derived from the charter."""
    out: list[str] = []
    out.append(f"# GitHub governance for {charter.project}")
    out.append("# Generated by `agenraci compile --target github`.")
    out.append("# AgenRACI does not enforce anything at runtime — review this, map the")
    out.append("# member names to GitHub @handles, and apply it in GitHub yourself.")
    out.append("")

    gated = {name: a for name, a in charter.actions.items() if a.gate is not None}

    # --- CODEOWNERS scaffold --------------------------------------------------
    out.append("# ── CODEOWNERS (starting point) ─────────────────────────────────")
    out.append("# A charter governs action TYPES, not file paths, so scope the glob(s)")
    out.append("# below to the parts of your repo each owner is accountable for.")
    owners = sorted({
        h for a in gated.values() for r in a.accountable
        for h in _humans_in_role(charter, r)
    })
    if owners:
        out.append(f"*    {_handles(owners)}")
    else:
        out.append("# (no human is accountable for a gated action — set owners by hand)")
    out.append("")

    # --- Branch protection checklist -----------------------------------------
    out.append("# ── Branch protection (from gated actions) ──────────────────────")
    if not gated:
        out.append("# No action declares a `gate:`, so nothing here requires approval. Add a")
        out.append("# gate to the actions that must never happen unilaterally.")
        return "\n".join(out) + "\n"

    out.append("# In Settings → Branches → Add branch protection rule, for each action:")
    for name, action in gated.items():
        gate = action.gate
        approvers = _humans_in_role(charter, gate.approver)
        who = (
            _handles(approvers) if approvers
            else f"role '{gate.approver}' (no human members — assign one)"
        )
        out.append("")
        out.append(f"# {name}")
        out.append(f"#   • Require a pull request before merging, approved by {who}.")

        if gate.on_timeout == "block":
            out.append("#   • Do NOT enable auto-merge "
                       "(charter on_timeout=block — never proceeds unreviewed).")
        elif gate.on_timeout == "proceed_if_low_risk":
            out.append("#   • Auto-merge tolerable for this action only "
                       "(charter on_timeout=proceed_if_low_risk; it is marked low-risk).")
        elif gate.on_timeout.startswith("escalate_to:"):
            esc = gate.on_timeout.split(":", 1)[1].strip()
            out.append(f"#   • On approver timeout, route the decision to role '{esc}' "
                       f"(charter {gate.on_timeout}).")

        if gate.break_glass is not None:
            bg = gate.break_glass
            after = "after-the-fact review required" if bg.requires_after_review \
                else "no after-review required"
            out.append(f"#   • Break-glass: '{bg.who}' may override when {bg.condition} "
                       f"({after}).")

    return "\n".join(out) + "\n"
